services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: todo-list-backend
    command: sh -c "./scripts/wait-for.sh todo-list-db:5432 && npm run dev"
    depends_on:
      - db
    env_file: ./.env
    environment:
      - NODE_ENV=development
      - SERVER_HOST=$SERVER_HOST
      - SERVER_PORT=$SERVER_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
    ports:
      - $SERVER_PORT:3001
  db:
    image: postgres
    restart: unless-stopped
    container_name: todo-list-db
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRESDB_LOCAL_PORT:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes: 
  db:
